from tkinter import *
import customtkinter

def morse_code(self):
    def convert():
        INPUT = inputtxt.get("1.0", "end-1c")
        def transform_numbers(a):
            a = a.replace("1", ".---- ")
            a = a.replace("2", "..--- ")
            a = a.replace("3", "...-- ")
            a = a.replace("4", "....- ")
            a = a.replace("5", "..... ")
            a = a.replace("6", "-.... ")
            a = a.replace("7", "--... ")
            a = a.replace("8", "---.. ")
            a = a.replace("9", "----. ")
            a = a.replace("0", "----- ")
            
            a = a.replace("a", ".- ")
            a = a.replace("b", "-... ")
            a = a.replace("c", "-.-. ")
            a = a.replace("d", "-.. ")
            a = a.replace("e", ". ")
            a = a.replace("f", "..-. ")
            a = a.replace("g", "--. ")
            a = a.replace("h", ".... ")
            a = a.replace("i", ".. ")
            a = a.replace("j", ".--- ")
            a = a.replace("k", "-.- ")
            a = a.replace("l", ".-.. ")
            a = a.replace("m", "-- ")
            a = a.replace("n", "-. ")
            a = a.replace("o", "--- ")
            a = a.replace("p", ".--. ")
            a = a.replace("q", "--.- ")
            a = a.replace("r", ".-. ")
            a = a.replace("s", "... ")
            a = a.replace("t", "- ")
            a = a.replace("u", "..- ")
            a = a.replace("v", "...- ")
            a = a.replace("w", ".-- ")
            a = a.replace("x", "-..- ")
            a = a.replace("y", "-.-- ")
            a = a.replace("z", "-.-- ")   
            
            a = a.replace("A", ".- ")
            a = a.replace("B", "-... ")
            a = a.replace("C", "-.-. ")
            a = a.replace("D", "-.. ")
            a = a.replace("E", ". ")
            a = a.replace("F", "..-. ")
            a = a.replace("G", "--. ")
            a = a.replace("H", ".... ")
            a = a.replace("I", ".. ")
            a = a.replace("J", ".--- ")
            a = a.replace("K", "-.- ")
            a = a.replace("L", ".-.. ")
            a = a.replace("M", "-- ")
            a = a.replace("N", "-. ")
            a = a.replace("O", "--- ")
            a = a.replace("P", ".--. ")
            a = a.replace("Q", "--.- ")
            a = a.replace("R", ".-. ")
            a = a.replace("S", "... ")
            a = a.replace("T", "- ")
            a = a.replace("U", "..- ")
            a = a.replace("V", "...- ")
            a = a.replace("W", ".-- ")
            a = a.replace("X", "-..- ")
            a = a.replace("Y", "-.-- ")
            a = a.replace("Z", "-.-- ")
                
            a = a.replace(" ", "  ")
            a = a.replace(",",",")
            
            return a
        print(INPUT)
        print(transform_numbers(INPUT))
        print("\n")
        
    if __name__=="__main__":    
        root = Tk()
        root.wm_attributes('-toolwindow', 'True')
        root.geometry("300x350")
        root.resizable(False, False)
        root.configure(bg="black")
        root.config(cursor = "top_left_arrow")
        root.title("Convert morse code")
        

        title = Label(root, text="Convert Morse Code", bg="black", font=("Arial", 20), fg="white")
        space = Label(root, bg="black", text=" ")
        space3 = Label(root, bg="black", text="Input text here...", fg="white")
        inputtxt = Text(root, width=25, height = 12)
        space4 = Label(root, bg="black", text=" ", fg="white")
        space1 = Label(root, bg="black", text=" ")
        credits = Label(root, text="© 2023 Z4que ALL RIGHTS RESERVED", background="black", font=("Arial", 10, ), fg="white")
        credits.place(x=30, y=320)
        title.pack()
        space.pack()
        space3.pack
        inputtxt.pack()
        space4.pack()
        button = Button(root, command = convert, background="white", activebackground="gray", text="Convert", width=15, height=2).pack()
        space1.pack()
            
        root.mainloop()